### ISSUE TITLE
zk-atoms do not persist

### ISSUE THREAD

**Issue by cch1** [liebke/avout#2]
I have noted that zk-atoms do not persist when the client connection is broken.  More details when available.

**Comment by jonpither** [comment]
Any update on this? It seems a massive inconsistency between the way refs and atoms are handled.

**Comment by aterreno** [comment]
@liebke ? Any light on this?

**Comment by juxtin** [comment]
This issue has been open a long time and I'm not sure what the whole history is, but it appears that it was fixed at some point. I've added a couple of tests to verify it and prevent any regression in the future.

For what it's worth, I also tried replicating this by setting a zk-atom on a remote computer and then abruptly disconnecting it (by turning off wifi). When I checked the atom from a local REPL, it had the correct value.

**Comment by juxtin** [comment]
So, bit of an oversight on my part. The tests were passing on my machine because I had another process connected to the ZK server, which apparently caused the zk-atoms to persist when they wouldn't have otherwise. Running the tests _correctly_ revealed that atoms do not persist, although refs do.

I've opened PR #16 to actually fix the issue, as verified by [Travis CI on my fork](https://travis-ci.org/holguinj/avout/builds/28746571).

**Comment by torsten** [comment]
Hi all, I had a similar issue and could not get atoms to work correctly and sync data across.

So I re-implemented only the atom part of avout in [zookeeper-atom](https://github.com/torsten/zookeeper-atom). We are using it production at work since ~4 months in case you are interested.

**Comment by hantuzun** [comment]
I run the same issue as well. I've chosen avout over zookeeper-atom since it seems like a bigger project but it loses the atoms state when the application disconnects. I've tried defining the connection with :persistance flag as well.

Over this problem I've tried  torsten's zookeeper-atom with no problem ;)
